server:
  port: 8080

spring:
  application:
    name: Ramashish.booking
  datasource:
    url: jdbc:mysql://localhost:3306/resourceBooking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Rama#9977
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        open-in-view: false

app:
  jwt:
    secret: "9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4"
    expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true